### ISSUE TITLE
Updating fingerprint file is not atomci

### ISSUE THREAD

**Issue by dpkds** [nabto/unabto#68]
fp_acl_file.c is implemented as if it saves/updated the persistence file atomically, but that's not the case.

A ffsync() is missing in fp_acl_file_save_file() before the rename().

On a slow flash file system this has been seen to result in an empty persistence file.

**Comment by mkm85** [comment]
What version is this behavior observed on?

On current master we do an fclose before the rename, we believe that should be enough to make the file written to the disk.
https://github.com/nabto/unabto/blob/master/src/modules/fingerprint_acl/fp_acl_file.c line 139 - 162

**Comment by dpkds** [comment]
From fclose man:
Note that fclose() flushes only the user-space buffers provided by the C library.  To ensure that the data is physically stored on disk the kernel buffers must be flushed too, for example, with sync(2) or fsync(2).

In my case I'm running on a ubifs where it could take very long for the data to reach the physical storage. However it could happen on any file system not mounted specifically with sync.

It's observed with version:
unabto_tunnel -V
Version: 3.0.15
... but the save functionality has not changed since.

**Comment by mkm85** [comment]
we will add fsync

**Comment by mkm85** [comment]
fsync added to master
