### ISSUE TITLE
Enhancement: Support Dart & flutter

### ISSUE THREAD

**Issue by ricksondpenha** [nabto/unabto#69]
Hello nabto team, Since google's flutter, a cross platform app development sdk has been taking over the development world, is there any support for unabto in flutter?

I'm looking for a simple Flutter package to connect, send/stream data from unabto devices to flutter apps. Since flutter uses dart, and **unabto** supports dartino, is there any way we can port it? Or will you guys give an official support for **Flutter** <3

**Comment by christiansiegel** [comment]
[unabto-dartino](https://github.com/nabto/unabto-dartino) is a wrapper library around the uNabto SDK for Dartino devices. Although both Dartino (device side) and Flutter (client side) use the Dart language they are different things. You are looking for the client-side libraries like the [android-client-api](https://github.com/nabto/android-client-api). You still have to implement [something in between](https://flutter.io/platform-channels/) to access e.g. the Android API from Flutter. This might be quite straight forward though.

disclaimer: this is not an official answer from the Nabto team :wink:

**Comment by mkm85** [comment]
We are not actively working on flutter on either the client or device side. But we look at the development and if support is coming is is most likely for the client. Until then you can create your own flutter wrapper around android and ios libraries.
