### ISSUE TITLE
RTSP streaming is not working

### ISSUE THREAD

**Issue by bidyutper** [nabto/unabto#79]
HI! 
I am getting RTSP stream which is plying in VLC well on gateway.
I followed https://www.nabto.com/rtsp-p2p-streaming-through-nabto/    guide but unable to view RTSP stream on mobile app.
On gateway termal showing
 `unabto_attach.c(563) State change from WAIT_GSP to ATTACHED` 
if I pass
`pi@rpi:~ $ ./unabto/apps/tunnel/unabto_tunnel \
  -d <id>\
  -k <key>\
  --allow-port <port> --allow-host <RTSP_IP> \
  --no-access-control` 
Only App showing device offline
How to get rtsp streaming work on app?

**Comment by nabto** [comment]
Hi,
The device is connected. "Attached" means attached to the basestation, ie. "alive and awaiting connections".
You need to pair on local network, then remote connect
Please use support@nabto.com for further questions.
